---
- name: Update APT package manager repositories cache
  become: true
  apt:
       update_cache: yes

- name: Install Java 8
  become: yes
  apt:
      name: "{{ item }}"
      state: present
  with_items:
     openjdk-8-jdk

- name: Install Tomcat
  become: True
  apt:
      name: tomcat8
  become_method: sudo

- name: Install Unzip
  become: yes
  apt:
      name: unzip
  become_method: sudo

- name: copy war file
  copy: src=./target/LoginWebApp-1.war dest=/var/lib/tomcat8/webapps/ROOT/LoginApp.war

- name: Unzip WAR file
  become: True
  unarchive:
     src=/var/lib/tomcat8/webapps/ROOT/LoginApp.war
     dest=/var/lib/tomcat8/webapps/ROOT/ copy=no mode=0755
     owner=tomcat8
     group=tomcat8
  become_method: sudo
  notify:
         - restart tomcat

- name: wait for tomcat to start
  wait_for: port={{http_port}}
